export const CartActionTypes = {
    TOGGLE_HIDDEN_CART: 'TOGGLE_HIDDEN_CART',
    TOGGLE_REDIRECT_HANDLER: 'TOGGLE_REDIRECT_HANDLER',
    ADD_FAVORITES: 'ADD_FAVORITES',
    REMOVE_FAVORITES: 'REMOVE_FAVORITES',
    ADD_CART: 'ADD_CART',
    REMOVE_CART: 'REMOVE_CART'
}